import { 
  svgAsPngUri, 
  saveSvg, 
  saveSvgAsPng 
} from 'save-svg-as-png';

const siteName = "理系地学入門 - SCIENCE to IMG";
const siteUrl = "https://i-earth.pages.dev";
	
// save-svg-as-pngのオプションを設定
const getOptions = (svgElement: SVGSVGElement, excludedElements: Element[], format?: 'svg' | 'png' | 'jpeg' | 'webp') => {
  const viewBox = svgElement.viewBox.baseVal;
  const width = viewBox.width;
  const height = viewBox.height;
  
  const options: any = {
    exclude: excludedElements,
    excludeUnusedCss: true, // 未使用のCSSを除去（サイズ削減の要）
    width: width,
    height: height,
    left: viewBox.x,
    top: viewBox.y,
    scale: 2, 
    
    modifyStyle: (styleText: string) => {
      // 1. まずCSSの内容を小文字にしてチェック
      const lowerStyle = styleText.toLowerCase();
      const isKatex = lowerStyle.includes('katex') || lowerStyle.includes('.katex');
      const isFontFace = lowerStyle.includes('@font-face');

      // 2. KaTeXでもフォント定義でもないCSS（Tailwindなど）は空にして削除
      if (!isKatex && !isFontFace) {
        return ""; 
      }

      // 3. 必要なスタイルだった場合、著作権コメントと
      //    ★重要★ KaTeXの重複表示バグ（MathMLが表示されてしまう）を防ぐスタイルを強制追加
      const fixKatexDoubleRender = `
        .katex-mathml { display: none !important; clip: rect(1px, 1px, 1px, 1px); border: 0; height: 1px; width: 1px; overflow: hidden; position: absolute; }
        .katex-html { display: block; }
      `;

      const comment = `/* Generated by ${siteName} (${siteUrl}) */`;
      return `${comment}\n${fixKatexDoubleRender}\n${styleText}`;
    },
  };

  // SVG形式でない場合（PNGなど）のみ、フォントファイルをCSSとして埋め込む
  // Vectorモード（MathJax）の場合はフォント不要だが、念のためHTMLモード用に残す
  if (format !== 'svg') {
    options.fontEmbedCss = `
      @font-face {
        font-family: 'KaTeX_Main';
        src: url('/fonts/KaTeX_Main-Regular.woff2') format('woff2');
        font-weight: normal;
        font-style: normal;
      }
    `;
  }
	
  return options;
};

// --- SVGエクスポート関数 ---
export const exportAsSVG = (svgElement: SVGSVGElement, filename: string, excludedElements: Element[]) => {
  const options = getOptions(svgElement, excludedElements, 'svg'); 
  saveSvg(svgElement, `${filename}.svg`, options);
};

// --- ラスタ画像エクスポート関数 ---
export const exportAsRaster = (
  svgElement: SVGSVGElement, 
  filename: string, 
  format: 'png' | 'jpeg' | 'webp',
  excludedElements: Element[]
) => {
  const options = getOptions(svgElement, excludedElements, format);
  
  if (format === 'png') {
    saveSvgAsPng(svgElement, `${filename}.png`, options);
    return;
  }
	
  svgAsPngUri(svgElement, options).then((uri: string) => {
    const img = new Image();
    img.onload = () => {
      const canvas = document.createElement('canvas');
      canvas.width = img.width;
      canvas.height = img.height;
      const ctx = canvas.getContext('2d');
      if (!ctx) return;

      if (format === 'jpeg') {
        ctx.fillStyle = 'white';
        ctx.fillRect(0, 0, canvas.width, canvas.height);
      }

      ctx.drawImage(img, 0, 0);
      canvas.toBlob(
        (blob) => {
          if (blob) {
            const link = document.createElement('a');
            link.href = URL.createObjectURL(blob);
            link.download = `${filename}.${format}`;
            link.click();
            URL.revokeObjectURL(link.href);
          }
        },
        `image/${format}`
      );
    };
    img.src = uri;
  });
};