import { 
  svgAsPngUri, 
  svgAsDataUri, 
  saveSvg, 
  saveSvgAsPng 
} from 'save-svg-as-png';

const siteName = "理系地学入門 - SCIENCE to IMG";
const siteUrl = "https://i-earth.pages.dev";
	
// save-svg-as-pngのオプションを設定
const getOptions = (svgElement: SVGSVGElement, excludedElements: Element[], format?: 'svg' | 'png' | 'jpeg' | 'webp') => {
  const viewBox = svgElement.viewBox.baseVal;
  const width = viewBox.width;
  const height = viewBox.height;
  
  const options: any = {
    exclude: excludedElements,
    // ★★★ 修正1: 未使用のCSSクラス（Tailwind等）を計算して除去するオプションを有効化 ★★★
    excludeUnusedCss: true,
    
    width: width,
    height: height,
    left: viewBox.x,
    top: viewBox.y,
    scale: 2, 
    
    // ★★★ 修正2: CSSのフィルタリングリングを強化 ★★★
    modifyStyle: (styleText: string) => {
      // スタイルテキストが KaTeX または フォント定義 を含まない場合、
      // Tailwindなどの不要なスタイルとみなして空文字を返す（除去する）
      const lowerStyle = styleText.toLowerCase();
      const isKatex = lowerStyle.includes('katex') || lowerStyle.includes('.katex');
      const isFontFace = lowerStyle.includes('@font-face');

      // KaTeXでもフォント定義でもない場合は、スタイルを破棄
      if (!isKatex && !isFontFace) {
        return ""; 
      }

      const comment = `/* Generated by ${siteName} (${siteUrl}) */`;
      return `${comment}\n${styleText}`;
    },
  };

  // SVG形式でない場合（PNGなど）にのみ、フォントを明示的に埋め込む設定
  // (SVGの場合は上のmodifyStyleとexcludeUnusedCssで抽出されたものが使われる)
  if (format !== 'svg') {
    options.fontEmbedCss = `
      @font-face {
        font-family: 'KaTeX_Main';
        src: url('/fonts/KaTeX_Main-Regular.woff2') format('woff2');
        font-weight: normal;
        font-style: normal;
      }
    `;
  }
	
  return options;
};

// --- SVGエクスポート関数 ---
export const exportAsSVG = (svgElement: SVGSVGElement, filename: string, excludedElements: Element[]) => {
  const options = getOptions(svgElement, excludedElements, 'svg'); 
  saveSvg(svgElement, `${filename}.svg`, options);
};

// --- ラスタ画像エクスポート関数 ---
export const exportAsRaster = (
  svgElement: SVGSVGElement, 
  filename: string, 
  format: 'png' | 'jpeg' | 'webp',
  excludedElements: Element[]
) => {
  const options = getOptions(svgElement, excludedElements, format);
  
  if (format === 'png') {
    saveSvgAsPng(svgElement, `${filename}.png`, options);
    return;
  }
	
  svgAsPngUri(svgElement, options).then((uri: string) => {
    const img = new Image();
    img.onload = () => {
      const canvas = document.createElement('canvas');
      canvas.width = img.width;
      canvas.height = img.height;
      const ctx = canvas.getContext('2d');
      if (!ctx) return;

      // JPGの場合、背景を白で塗りつぶす
      if (format === 'jpeg') {
        ctx.fillStyle = 'white';
        ctx.fillRect(0, 0, canvas.width, canvas.height);
      }

      ctx.drawImage(img, 0, 0);
      canvas.toBlob(
        (blob) => {
          if (blob) {
            const link = document.createElement('a');
            link.href = URL.createObjectURL(blob);
            link.download = `${filename}.${format}`;
            link.click();
            URL.revokeObjectURL(link.href);
          }
        },
        `image/${format}`
      );
    };
    img.src = uri;
  });
};