import { 
  svgAsPngUri, 
  svgAsDataUri, 
  saveSvg, 
  saveSvgAsPng 
} from 'save-svg-as-png';

const siteName = "理系地学入門 - SCIENCE to IMG";
const siteUrl = "https://(あなたのサイトのURL)";

// save-svg-as-pngのオプションを設定
const getOptions = (svgElement: SVGSVGElement, format?: 'png' | 'jpeg' | 'webp') => {
  const viewBox = svgElement.viewBox.baseVal;
  const width = viewBox.width;
  const height = viewBox.height;
  // SVG内のKaTeXフォントをインライン化するための設定
  const katexFontRegex = /@font-face\s*{[^}]*font-family:\s*KaTeX_Main[^}]*}/g;
  
  const elementToExclude = document.getElementById('grid-area');
	
  return {
    // グリッドを非表示にするためのCSSセレクタ
    exclude: [elementToExclude],
    
    // SVGのクレジットを追加するためのmodifier
    modifyStyle: (styleText: string) => {
      const comment = `/* Generated by ${siteName} (${siteUrl}) */`;
      return `${comment}\n${styleText}`;
    },
    
    // KaTeXのフォントをData URIとして埋め込む（これがTainted Canvasを防ぐ鍵）
    fontEmbedCss: `
      @font-face {
        font-family: 'KaTeX_Main';
        src: url('/fonts/KaTeX_Main-Regular.woff2') format('woff2');
        font-weight: normal;
        font-style: normal;
      }
      /* 他のKaTeXフォント（Italic, Boldなど）も同様に追加 */
    `,
    width: width,
    height: height,
    left: viewBox.x,
    top: viewBox.y,
		scale: 2, 
  };
};

// --- SVGエクスポート関数 ---
export const exportAsSVG = (svgElement: SVGSVGElement, filename: string) => {
  const options = getOptions(svgElement);
  saveSvg(svgElement, `${filename}.svg`, options);
};

// --- ラスタ画像エクスポート関数 ---
export const exportAsRaster = (
  svgElement: SVGSVGElement, 
  filename: string, 
  format: 'png' | 'jpeg' | 'webp',
) => {
  const options = getOptions(svgElement, format);
  
	if (format === 'png') {
    saveSvgAsPng(svgElement, `${filename}.png`, options);
    return;
  }
	
  svgAsPngUri(svgElement, options).then((uri: string) => {
    const img = new Image();
    img.onload = () => {
      const canvas = document.createElement('canvas');
      canvas.width = img.width;
      canvas.height = img.height;
      const ctx = canvas.getContext('2d');
      if (!ctx) return;

      // JPGの場合、背景を白で塗りつぶす（透過がサポートされないため）
      if (format === 'jpeg') {
        ctx.fillStyle = 'white';
        ctx.fillRect(0, 0, canvas.width, canvas.height);
      }

      ctx.drawImage(img, 0, 0);
      canvas.toBlob(
        (blob) => {
          if (blob) {
            const link = document.createElement('a');
            link.href = URL.createObjectURL(blob);
            link.download = `${filename}.${format}`;
            link.click();
            URL.revokeObjectURL(link.href);
          }
        },
        `image/${format}`
      );
    };
    img.src = uri;
  });
};